### ISSUE TITLE
Header/Navigation erstellen

### ISSUE THREAD

**Issue by robinaeschlimann** [joshua-lehmann/SmashGrade#40]
Ein Header inkl. Navigation soll für Mobile und Desktop erstellt werden

**Comment by JasminKeller** [comment]
Todo's:

- [ ] Logo einbinden
- [x] URLs mit Trennstrichen z.B: user-management
- [x] routes async machen
- [x] Link anstelle von onClick
- [x] in die übersetzung einbauen (i18n)
