### ISSUE TITLE
Design und Farbkonzept festlegen und im Theme implementieren

### ISSUE THREAD

**Issue by joshua-lehmann** [joshua-lehmann/SmashGrade#7]
Gemeinsam mit dem Design Team abklären [welche Farben](https://ant.design/docs/spec/colors) verwendet werden (background, container/Komponenten wie buttons, Schriftfarbe usw.) sollen und allfällige sonstige Styling Regeln (Borders, Rundungen, Shadows etc.). Diese dann in der Doku festhalten und im Ant Design Theme Global für die React App implementieren: https://ant.design/docs/react/customize-theme

**Comment by JasminKeller** [comment]
**Design Konzept in Figma Visualisiert**
https://www.figma.com/file/umOKw8yF0RbQyPkU4B7bIe/SmashGrade?type=design&node-id=111%3A2817&mode=design&t=LUZdsd2UZXlhkCed-1

**Sandbox - Erste Umsetzung des Designs in React mit Ant-Design**
https://codesandbox.io/s/sandpack-project-forked-xn8v3y?file=/app.tsx


**Next Up:** 

- [x] Mockup mit Versionierung überarbeiten
- [x] Mockups für Popups und Login Page
- [x] Erste Designs umsetzen im Projekt
- [x] Wiki bezüglich Design erstellen

**Comment by JasminKeller** [comment]
Documentation: Design & Theme Guideline

https://github.com/SmashGrade/SmashGrade-App/wiki/Design-&-Theme-Guideline
