### ISSUE TITLE
Übersetzung und Internationalisierung gemäss i18n

### ISSUE THREAD

**Issue by joshua-lehmann** [joshua-lehmann/SmashGrade#8]
Möglichkeiten anschauen und analysieren, um eine React App gemäss i18n Standard zu übersetzen und zu internationalisieren.
Eine populäre Library scheint [i18next](https://react.i18next.com/) zu sein. Es können aber auch andere Libs/Möglichkeiten angeschaut werden.

Das Resultat dieses Tickets soll die Empfehlung einer Library sein und diese soll in dem Projekt installiert und konfiguriert werden und ein Beispiel den anderen Teammitgliedern vorgestellt werden.

**Comment by joshua-lehmann** [comment]
@theGreyPilgrim42 Bitte auch kurze Zusammenfassung der Entscheidung und kurzes "how to use" [im Wiki dokumentieren](https://github.com/SmashGrade/SmashGrade-App/wiki).

**Comment by theGreyPilgrim42** [comment]
Die Dokumentierung der Entscheidung und eine kurze Anleitung ist im [Wiki](https://github.com/SmashGrade/SmashGrade-App/wiki/I18N%E2%80%90Analyse) ersichtlich.
